library(pheatmap)
data<-read.table("/opt/mnt/biogfs5/wanghengtao/Fuwai/Cardiovascular/dutp/4-CUFF/CUFFNORM_NEW/GROUP/genes.fpkm_table",row.names=1,header=T,sep="\t")
colnames(data)<-c("N56","N65","N64","N71","N63","J-1","J-2","J-3","S26","S20","S17","S21","S15","S16","S24","S12","S22")
data2<-log2(data+1)
pdf("/opt/mnt/biogfs5/wanghengtao/Fuwai/Cardiovascular/dutp/4-CUFF/RESULTS/fpkm_pearson_heatmap.pdf")
matrix2=cor(data2)
pheatmap(matrix,cluster_rows=T,cluster_cols=T,display_numbers=T,fontsize_number=6,number_format = "%.2f") 
dev.off()
data10<-log10(data+1)
matrix10=cor(data10)
pdf("/opt/mnt/biogfs5/wanghengtao/Fuwai/Cardiovascular/dutp/4-CUFF/RESULTS/fpkm_pearson_heatmap10.pdf")
pheatmap(matrix10,cluster_rows=T,cluster_cols=T,display_numbers=T,fontsize_number=6,number_format = "%.2f") 
dev.off()